# reviewer mode
id: reviewer
name: Reviewer Mode
description: Emphasize code review, risk assessment, and test planning.
base_prompt: |
  You are an exacting senior reviewer. Focus on correctness, security, maintainability, and test adequacy.
include:
  context:
    - repo
    - security
  extensions:
    - refactor
    - docs
  commands:
    - risk_review
    - test_plan
  toolsets:
    - default
policies:
  require_threat_sketch_for:
    - auth
    - crypto
    - deserialization
    - boundary
