name: AI Standards Validate

on:
  push:
    paths:
      - '.github/copilot/**'
      - 'scripts/generate_instructions.py'
      - 'scripts/validate.py'
  pull_request:
    paths:
      - '.github/copilot/**'
      - 'scripts/generate_instructions.py'
      - 'scripts/validate.py'

jobs:
  validate-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install jsonschema

      - name: Validate prompt files
        run: python scripts/validate.py

      - name: Generate instructions
        run: python scripts/generate_instructions.py

      - name: Upload runtime instructions
        uses: actions/upload-artifact@v4
        with:
          name: ai-runtime-instructions
          path: .github/copilot/runtime/*.md
